# Generated by Django 2.0.5 on 2019-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dog_App', '0002_dog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='doc',
            field=models.FileField(default='Doc/None/No-docs.pdf', upload_to='Doc/'),
        ),
    ]
