# Generated by Django 2.0.5 on 2019-03-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dog_App', '0003_dog_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='doc',
            field=models.FileField(default='Doc/None/No-docs.PDF', upload_to='Doc/'),
        ),
    ]
